### ISSUE TITLE
Error during orders dialog

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/bot-survey-engine#7]
```
...BotBuilder:prompt-text - Session.send()
...BotBuilder:prompt-text - Session.sendBatch() sending 1 message(s)
{"type":"send","message":"For privacy reasons, I won't confirm I have your order.  But assuming it's there, what seems to be the issue?","user":"User"}
ChatConnector: message received.
{"type":"recieve","message":"baladf","user":"User"}
UniversalBot("*") routing "baladf" from "emulator"
Library("BotBuilder").findRoutes() explanation:
	ActiveDialog(0.5)
...BotBuilder:prompt-text - Prompt.returning(baladf)
...BotBuilder:prompt-text - Session.endDialogWithResult()
..store - waterfall() step 5 of 5
ReferenceError: ses is not defined
    at Array.waterfall (/Users/kylepolich/git/ds/dataskeptic-bot/dialogs/store.js:50:3)
    at /Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.dialogResumed (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:46:14)
    at Session.endDialogWithResult (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/Session.js:358:28)
    at PromptText.Prompt.invokeIntent (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/Prompt.js:331:21)
    at PromptText.Prompt.replyReceived (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/dialogs/Prompt.js:147:18)
    at Session.routeToActiveDialog (/Users/kylepolich/git/ds/dataskeptic-bot/node_modules/botbuilder/lib/Session.js:525:24)
..store - ERROR: ses is not defined
..store - Session.endConversation()
Session.sendBatch() sending 2 message(s)
{"type":"send","message":"Oops. Something went wrong and we need to start over.","user":"User"}
{"type":"send","user":"User"}
```

**Comment by kylepolich** [comment]
Opened by accident, this should be in the other repo
